import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import supabaseComponentClient from "@/utils/supabaseServer";
import Login from "@/components/Login";
import { camelize } from "@/utils/utils";
import Providers from "./providers";
import {  Dropdown,  DropdownTrigger,  DropdownMenu,  DropdownSection,  DropdownItem} from "@nextui-org/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await supabaseComponentClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  let userData;
  if (user) {
    const userDataResponse = await supabase
      .from("users")
      .select()
      .eq("id", user.id);

    userData = camelize(userDataResponse.data?.[0]);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex items-center justify-between p-6 md:p-10">
            <div className="flex justify-self-center"> 
              <Link href={"/"}className="justify-self-start, text-xl font-bold">Anime guide</Link>
              <Link href={"/search"} className="justify-self-start, text-xl font-bold pl-10">Discover</Link>
            </div>
            <div>
              <Login user={user} userData={userData} />
            </div>
          </div>
          <main className="p-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
