import Login from "@/components/Login";
import { supabaseServerComponentClient } from "@/utils/supabaseServer";
import { camelize } from "@/utils/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await supabaseServerComponentClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  let userData;
  if (user) {
    const userDataResponse = await supabase
      .from("users")
      .select()
      .eq("id", user.id);

    userData = camelize(userDataResponse.data?.[0]);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex items-center justify-between p-6 md:p-10">
            <div className="flex justify-self-center">
              <Link
                href={"/"}
                className="justify-self-start, text-xl font-bold"
              >
                Anime guide
              </Link>
              <Link
                href={"/search"}
                className="justify-self-start, pl-10 text-xl font-bold"
              >
                Discover
              </Link>
            </div>
            <div>
              <Login user={user} userData={userData} />
            </div>
          </div>
          <main className="p-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
